#! /usr/bin/env python3

import hobo_core
import hobo_coreutils
import urllib.request

server = "https://cse-linux-01.unl.edu/~dbrozovic2/mtg/data/"

try:
    with urllib.request.urlopen(server + "latest.txt", timeout=10) as f:
        server_latest = f.read().decode("utf-8")
except urllib.error.URLError as e:
    server_latest = None
    hobo_core.show_warning("Cannot reach price database.")
try:
    with open("data/latest.txt", "r", encoding="utf-8") as f:
        local_latest = f.read()
except FileNotFoundError as e:
    local_latest = None

if server_latest != local_latest and server_latest != None:
    with urllib.request.urlopen(server + server_latest + ".json") as f, \
         open("data/" + server_latest + ".json", "w") as g:
        g.write(f.read().decode("utf-8"))

    with open("data/latest.txt", "w") as f:
        f.write(server_latest)

price_list = hobo_core.PriceList()
deck = hobo_core.Deck()

while True:
    raw = input(">>> ")
    tokens = hobo_coreutils.parse_tokens(raw)
    cmdname = tokens[0]
    cmdpath = f"commands/{cmdname}.py"
    try:
        f = open(cmdpath)
    except FileNotFoundError:
        hobo_core.show_error(f"No command named {cmdname}.")
    else:
        with f:
            code = compile(f.read(), cmdpath, "exec")
            exec(code, None, {
                "args": tokens[1:]
            })
